### ISSUE TITLE
Uncaught RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by aljubaer** [DeepARSDK/photoedit-web-js#1]
I am trying to run the project and it works properly for the given test photos. But it is getting this error while I want to process/load some of my photos. 

> deepar.wasm:0x3b91 Uncaught RuntimeError: memory access out of bounds
>     at Xe (http://localhost:8888/lib/deepar.wasm:wasm-function[314]:0x3b91)
>     at Object.e.switchEffectByteArray (http://localhost:8888/lib/deepar.js:1:2619)
>     at XMLHttpRequest.z.onreadystatechange (http://localhost:8888/lib/deepar.js:1:2898)

The use-case of having this error is: 
1. Load one of the test photos.
2. Load another photo. (Not test photo)
3. Apply filter.

**Comment by Sikter** [comment]
Can you provide a photo example that produces the error? Thanks.

**Comment by aljubaer** [comment]
Sure, here are some photos. Load them one after another accordingly
[Photo1](https://cloud.squidex.io/api/assets/virtual-try-on/05da8199-7b89-4c79-8874-2ec143bc0f70)
[Photo2](https://cloud.squidex.io/api/assets/virtual-try-on/4a59bfa3-5244-4756-af7a-b1dbea3b8a22)
[Photo3](https://cloud.squidex.io/api/assets/virtual-try-on/be5fe4a2-e94d-4f68-9ded-1e9d923f9cae)
If photo1 is not loaded no error occurs however If photo1 is loaded then photo2 or photo3 then the error happens.
You can test from [my test website](https://aljubaer.github.io/photo-edit-web/)
Follow the steps:
1. Load photo1
2. Load photo4
3. Load photo3
4. Apply to makeup

**Comment by Krucksy** [comment]
Any updates ?
